# OFO因子复现

In [1]:
from jaqs_fxdayu.util import dp
from jaqs.data.dataapi import DataApi

start = 20160101
end = 20180101

api = DataApi(addr='tcp://data.tushare.org:8910')
api.login("18813099800", 
          'eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MjE3OTg3OTc5NjciLCJpc3MiOiJhdXRoMCIsImlkIjoiMTg4MTMwOTk4MDAifQ.FoiEBamI0pAGNbmxW51UWiulBKWqPWH4EAa6Z7_CkO8'
)

ZZ800_id = dp.index_cons(api, "000906.SH", start, end)

stock_symbol = list(set(ZZ800_id.symbol.values))

In [2]:
import jaqs_fxdayu
jaqs_fxdayu.patch_all()
from jaqs.data import DataView
from jaqs.data import RemoteDataService
from jaqs_fxdayu.data.dataservice import LocalDataService
import os
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

dataview_folder = '../data'
dv = DataView()
ds = LocalDataService(fp=dataview_folder)


factor_list = ['volume']
check_factor = ','.join(factor_list)

dv_props = {'start_date': start, 'end_date': end, 'symbol':','.join(stock_symbol),
         'fields': check_factor,
         'freq': 1,
         "prepare_fields": True}

dv.init_from_config(dv_props, data_api=ds)
dv.prepare_data()

/Users/fanglihan/anaconda/lib/python3.6/importlib/__init__.py:126: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return _bootstrap._gcd_import(name[level:], package, level)
/Users/fanglihan/anaconda/lib/python3.6/site-packages/jaqs/research/signaldigger/plotting.py:10: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/Users/fanglihan/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/fanglihan/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-7b614fd5a4b6>", line 1, in <module>
    from jaqs_fxdayu.util import dp
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/jaqs_fxdayu/__init__.py", line 4, in <module>
    import matplotlib.pyplot  # 防止被JAQS重载
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/fanglihan/anaconda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  mpl.use('Agg')

Initialize config success.
Query data...
Query data - query...
NOTE: price adjust method is [post adjust]
当前请求daily...
{'adjust_mode': None, 'fields': 'trade_status,volume,close_adj,open_adj,high_adj,vwap_adj,low_adj,open,high,close,symbol,trade_date,vwap,low'}
下载进度946/981.
当前请求daily...
{'adjust_mode': 'post', 'fields': 'open,high,close,vwap,low,symbol,trade_date'}
下载进度946/981.
WARNING: some data is unavailable:
    At fields 000748.SZ, 600005.SH
Query data - daily fields prepared.
Query instrument info...
Query adj_factor...
Data has been successfully prepared.

### SpearmanCheck函数

In [3]:
import scipy.stats as scst
import jaqs.util as jutill


def spearman_factor(factor_u='factor_u', factor_j='factor_j', start=20160101, symbol=stock_symbol):
    factors = dict()
    factors["factor_u"] = dv.get_ts(factor_u).loc[start:][stock_symbol].stack()
    factors["factor_j"] = dv.get_ts(factor_j).loc[start:][stock_symbol].stack()

    factors_df = pd.concat(factors.values(),axis=1)
    factors_df.columns = factors.keys()
    factors_df = jutill.fillinf(factors_df).dropna()

    # 两个因子的spearman相关性
    def get_factors_daily_corr(factors_df,
                               f1="factor_u",
                               f2="factor_j"):
        def _cal_corr(df):
            return scst.spearmanr(df[f1], df[f2])[0]

        result = factors_df.groupby(['trade_date']).apply(_cal_corr)
        result = pd.DataFrame(result)
        result.columns = ['spearmanr']
        return result

    result = get_factors_daily_corr(factors_df,"factor_u","factor_j")
    t_stat, p_value = scst.ttest_1samp(result, 0)
    return result.mean(), p_value # 相关关系均值,相关关系均值的ｔ统计量的p_value

## 1.Variance20
### 20日收益方差，因子值为年化后的值（等于日度方差*250）

In [4]:
variance20 = dv.add_formula('variance20_j','StdDev(close/Delay(close,1)-1,20)^2*250', is_quarterly=False, add_data=True)

In [5]:
dv.add_field('variance20')

Field name [variance20] not valid, ignore.

False

## 2.AR

In [6]:
AR = dv.add_formula("AR_J","Ts_Sum(high-open,26)/Ts_Sum(open-low,26)",is_quarterly=False,add_data=True)

In [7]:
dv.add_field('AR', ds)

Query data - query...
当前请求query...
{'fields': 'AR', 'view': 'factor'}
下载进度946/981.
WARNING: some data is unavailable:
    At fields 000748.SZ, 600005.SH
Query data - daily fields prepared.

True

In [8]:
print(spearman_factor(factor_u='AR', factor_j='AR_J', start=20160101, symbol=stock_symbol))

(spearmanr    0.984517
dtype: float64, array([0.]))

## 3.DBCD
### $BIAS = (close/MA(close,n)-1)*100$
### $DIF = BIAS(t) - BIAS(t-M)$
### $DBCD = EMA(DIF,T,1)$
### $N=5,M=16,T=17$

In [9]:
BIAS = dv.add_formula('BIAS_J',"(close/Ta('MA',0,close,close,close,close,close,5)-1)*100",is_quarterly=False,add_data=True)
DIF = dv.add_formula('DIF_J','BIAS-Delay(BIAS,16)',is_quarterly=False,add_data=True)
def sma(df, n, m):
    a = n / m - 1
    r = df.ewm(com=a, axis=0, adjust=False)
    return r.mean()
DBCD = dv.add_formula('DBCD_J',"SMA(DIF,17,1)",is_quarterly=False,add_data=True,register_funcs={"SMA":sma})

000748.SZ数据缺失严重,无法完成指标计算,请检查是否存在数据问题.
600005.SH数据缺失严重,无法完成指标计算,请检查是否存在数据问题.
Variable [BIAS] is not recognized (it may be wrong),try to fetch from the server...
Field name [BIAS] not valid, ignore.
Variable [DIF] is not recognized (it may be wrong),try to fetch from the server...
Query data - query...
当前请求query...
{'fields': 'DIF', 'view': 'factor'}
下载进度946/981.
WARNING: some data is unavailable:
    At fields 000748.SZ, 600005.SH
Query data - daily fields prepared.

In [10]:
dv.add_field('DBCD')

Query data - query...
当前请求query...
{'fields': 'DBCD', 'view': 'factor'}
下载进度946/981.
WARNING: some data is unavailable:
    At fields 000748.SZ, 600005.SH
Query data - daily fields prepared.

True

In [11]:
print(spearman_factor(factor_u='DBCD', factor_j='DBCD_J', start=20160101, symbol=stock_symbol))

(spearmanr   -0.04513
dtype: float64, array([2.07241742e-09]))

## 4.Alpha30
### $WMA((REGRESI(CLOSE/DELAY(CLOSE)-1,MKT,SMB,HML,60))^2,20)$

In [113]:
dv.add_field('PB')
dv.add_field('LCAP')
df, msg = api.daily(symbol='000906.SH', start_date=start,end_date=end, fields='close',adjust_mode='post')
df = df.set_index('trade_date')
R_M = df.close.pct_change()[1:]
close = dv.get_ts('close')
R = close/close.shift(1)-1
returns = dv.get_ts('close').pct_change()
PB = 1/dv.get_ts('PB')
LCAP = dv.get_ts('LCAP')

Field name [PB] already exists.
Field name [LCAP] already exists.

In [156]:
def percentile_30(row):
    s = row[1]
    point = np.percentile(s, 30)
    return {code: True for code in s[s<point].index}

def percentile_70(row):
    s = row[1]
    point = np.percentile(s, 70)
    return {code: True for code in s[s>point].index}

MB_30 = pd.DataFrame(map(percentile_30, LCAP.iterrows()), LCAP.index)
MB_70 = pd.DataFrame(map(percentile_70, LCAP.iterrows()), LCAP.index)
PB_30 = pd.DataFrame(map(percentile_30, PB.iterrows()), PB.index)
PB_70 = pd.DataFrame(map(percentile_70, PB.iterrows()), PB.index)

pipe = pd.Panel({'MB_30':MB_30, 'MB_70':MB_70, 'PB_30':PB_30, 'PB_70':PB_70,'returns':R_M})
pipe['MB_30'].fillna(False, inplace=True)
pipe['MB_70'].fillna(False, inplace=True)
pipe['PB_30'].fillna(False, inplace=True)
pipe['PB_70'].fillna(False, inplace=True)
print(pipe)

R_biggest = pipe[pipe['MB_70']]['returns'].groupby(level=0).mean()
R_smallest = pipe[pipe['MB_30']]['returns'].groupby(level=0).mean()
R_highpb = pipe[pipe['PB_70']]['returns'].groupby(level=0).mean()
R_lowpb = pipe[pipe['PB_30']]['returns'].groupby(level=0).mean()

SMB = R_smallest - R_biggest
HML = R_highpb - R_lowpb

AssertionError: Length of data and index must match

In [ ]:
import talib as ta
constant = pd.Series(np.ones(len(R.index)), index=R.index)
df = pd.DataFrame({'R': R,'M': R_M,'SMB': SMB,'HML': HML,'Constant': constant})
df = df.dropna()

model = pd.stats.ols.MovingOLS(y = df['R'], x=df[['M', 'SMB', 'HML']],window_type='rolling', window=60)
alpha30 = df['R'] - model.y_predict
alpha30 = ta.WMA(alpha30, timeperiod=20)
dv.append_df(alpha30,'Alpha30')

## 5.Alpha73
### $((TSRANK(DECAYLINEAR(DECAYLINEAR(CORR((CLOSE),VOLUME,10),16),4),5),-RANK(DECAYLINEAR(CORR(VWAP, MEAN(VOLUME,30), 4),3))) * -1)$

In [13]:
alpha73 = dv.add_formula('alpha73',"-1*(Ts_Rank(Decay_linear(Decay_linear(Correlation(close,volume,10),16),4),5)-Rank(Decay_linear(Correlation(vwap,Ts_Mean(volume,30),4),3)))",is_quarterly=False,add_data=True)
alpha73.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20160104,501.0,NaN,397.0,234.0,417.0,7.0,457.0,809.0,835.0,NaN,...,NaN,NaN,NaN,NaN,NaN,63.0,41.0,NaN,723.0,799.0
20160105,194.0,NaN,524.0,368.0,511.0,20.0,559.0,719.0,800.0,NaN,...,NaN,NaN,NaN,NaN,NaN,33.0,40.0,NaN,201.0,817.0
20160106,212.0,NaN,685.0,562.0,577.0,30.0,611.0,371.0,706.0,NaN,...,NaN,NaN,NaN,NaN,NaN,53.0,44.0,NaN,231.0,417.0
20160107,263.0,NaN,795.0,696.0,702.0,29.0,558.0,171.0,690.0,NaN,...,NaN,NaN,NaN,NaN,NaN,152.0,44.0,NaN,225.0,276.0
20160108,361.0,NaN,747.0,698.0,738.0,23.0,676.0,45.0,637.0,NaN,...,NaN,NaN,NaN,NaN,NaN,261.0,61.0,NaN,223.0,109.0

## 6.Alpha116
### $REGBETA(CLOSE,SEQUENCE,20)$

In [35]:
close = dv.get_ts("close_adj").dropna(how='all', axis=1)
Alpha116 = pd.DataFrame({sec_symbol: -ta.LINEARREG_SLOPE(value.values, 20) for sec_symbol, value in close.iteritems()}, index=close.index)
dv.append_df(Alpha116,'Alpha116')
dv.get_ts("Alpha116").tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,1.155654,17.051851,-7.002425e-14,-0.040595,0.236610,1.642876,-0.549210,0.200561,-0.027074,0.566080,...,-0.691135,0.191059,-0.006943,-0.333930,0.000582,-0.252034,-0.225591,-0.086384,-0.320261,0.088619
20171226,-0.247695,15.348011,-7.002425e-14,-0.109646,0.218144,1.595254,-0.571222,0.220684,-0.031587,0.481754,...,-0.703150,0.153443,-0.007258,-0.353095,0.034412,-0.309322,-0.243796,-0.075675,-0.289542,0.094817
20171227,-1.311326,6.871096,-7.002425e-14,-0.155215,0.174605,1.460541,-0.485777,0.180707,-0.027704,0.344943,...,-0.661865,0.142111,0.002099,-0.347421,0.043706,-0.297250,-0.250775,-0.038527,-0.243151,0.083369
20171228,-1.631105,3.223169,-7.002425e-14,-0.217699,0.145029,1.361219,-0.443814,0.179334,-0.037464,0.168010,...,-0.580827,0.120901,0.029669,-0.345553,0.040230,-0.300432,-0.246094,-0.014675,-0.184719,0.045889
20171229,-1.496138,-0.193159,-7.002425e-14,-0.353015,0.105168,1.164430,-0.497054,0.181968,-0.050686,-0.148095,...,-0.536451,0.092870,0.011425,-0.370025,0.037719,-0.319309,-0.243363,-0.021725,-0.156271,0.012590

## 7.Alpha120
### $(RANK((VWAP - CLOSE)) / RANK((VWAP + CLOSE)))$

In [16]:
alpha120 = dv.add_formula('Alpha120','Rank(vwap-close)/Rank(vwap+close)',is_quarterly=False,add_data=True)
alpha120.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20160104,0.656347,0.066282,1.231834,1.230769,0.830709,0.871060,1.137705,0.993485,1.358079,0.002503,...,NaN,NaN,0.086047,NaN,NaN,0.891685,0.887898,NaN,1.069494,3.090909
20160105,1.905882,0.053476,1.740351,0.974110,1.398390,1.203438,2.758503,1.010858,2.682403,0.002469,...,NaN,NaN,0.753394,NaN,NaN,1.015368,1.121762,NaN,0.097335,21.115385
20160106,2.514881,0.058333,2.014286,2.676471,1.055888,1.432665,2.468531,0.088937,3.350649,0.002469,...,NaN,NaN,1.022321,NaN,NaN,0.078947,0.812903,NaN,0.148446,22.774194
20160107,0.447059,0.057644,0.892193,1.048860,1.062626,1.324561,1.316364,0.997843,1.431111,0.002415,...,NaN,NaN,0.179318,NaN,NaN,0.992341,1.018205,NaN,0.987327,3.793103
20160108,1.614731,0.060453,2.381481,1.912752,0.877800,1.178363,1.930657,0.085221,2.417040,0.002413,...,NaN,NaN,0.091803,NaN,NaN,0.319780,0.169251,NaN,0.089143,16.733333

## 8.Alpha121
### ((RANK((VWAP - MIN(VWAP, 12)))^TSRANK(CORR(TSRANK(VWAP, 20), TSRANK(MEAN(VOLUME,60), 2), 18), 3)) *-1)

In [15]:
alpha121 = dv.add_formula('Alpha121','(Rank(vwap-Ts_Min(vwap,12)))^(Ts_Rank(Correlation(Ts_Rank(vwap,20),Ts_Rank(Ts_Mean(volume,60),2),18),3))',is_quarterly=False,add_data=True)
alpha121.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000025.SZ,000027.SZ,000028.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20160104,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0
20160105,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0
20160106,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20160107,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
20160108,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN